[package]
name = "magic-number-a"
version = "0.1.0"
authors = ["Glen Mailer <glenjamin@gmail.com>"]
description = "A dummy module for experimenting with dependency resolution"
license = "MIT"

[dependencies]
magic-number = "0.1.0"
